SET AUTOCOMMIT OFF;

DROP TABLE ESTDISPONIBLE;
DROP TABLE AssurePermanence;
DROP TRIGGER trigger_verif_offre;
DROP TRIGGER trigger_incr_Contrat_ID;
DROP SEQUENCE ContratID;
DROP TABLE Contrat;
DROP TABLE Quantite;
DROP TRIGGER trigger_incr_Offre_ID;
DROP SEQUENCE OffreID;
DROP TABLE Offre;
DROP TABLE Utilisateur;

COMMIT; 
SET AUTOCOMMIT ON;
